spec:
  template:
    spec:
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry
      containers:
      - volumeMounts:
        - name: registry
          mountPath: /home/hono/device-registry
